---

# Runtime
verbose: 3
token: lstbknd
name: "lastbackend"
description: "lastbackend cluster"

# Etcd database
etcd:
  prefix: lastbackend
  endpoints:
    "127.0.0.1:2379"

# Domain
domain:
  internal: "lb.local"
  external: "undassa.lbdp.io"

server:
  host: 0.0.0.0
  tls:
    insecure: true
    ca: "/opt/cert/lastbackend/ca.pem"
    cert: "/opt/cert/lastbackend/server.pem"
    key: "/opt/cert/lastbackend/server-key.pem"
