---

# Runtime
verbose: 3
token: lstbknd

# Cluster info
name: "lastbackend"
description: "lastbackend cluster"

# System domains settings
domain:
  internal: "lb.local"
  external: "undassa.lbdp.io"

# Etcd database
storage:
  driver: "etcd"
  etcd:
    prefix: lastbackend
    endpoints:
      "127.0.0.1:2379"

# Cluster http-server settings
server:
  host: 0.0.0.0
  tls:
    insecure: true

# Last.Backend vault service settings
vault:
  endpoint: http://127.0.0.1:2965
  token: fca7678528b749db863d04cd9ec27d89