---
# Runtime
verbose: 3
token: lstbknd
workdir: "/private/var/lib/lastbackend/runtime/"

api:
  uri: "127.0.0.1:2967"
  tls:
    insecure: true

server:
  host: 0.0.0.0
  port: 2969
  tls:
#    insecure: true

# Container
container:
  docker:
    version: 1.35
  cri:
    type: "docker"
  iri:
    type: "docker"
  csi:
    dir:
      root: "/private/var/lib/lastbackend/volumes/"